packages:
  - "apps/*"
  - "services/*"
  - "packages/*"
  - "frontend"
  - "backend"
  - "shared"

onlyBuiltDependencies:
  - esbuild
  - msgpackr-extract
  - sharp
allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: true
